FROM maven:3.5-jdk-8-alpine as build
WORKDIR /app
COPY . .
RUN mvn install -Dmaven.test.skip=true


FROM tomcat:8.5-alpine
WORKDIR /app
COPY --from=build /app/target/fastandfoodius.war /usr/local/tomcat/webapps/
COPY --from=build /app/lib/mysql-connector-java-8.0.18.jar  /usr/local/tomcat/lib/

EXPOSE 8080

CMD ["catalina.sh","run"]





